version: 2

build:
    image: stable

conda:
    environment: .rtd-environment.yml

python:
    version: 3.8
    install:
      - method: pip
        path: .
        extra_requirements:
          - docs
