name: nrlmsise00

channels:
    - conda-forge

dependencies:
    - python=3
    - ipython
    - numpy
    - numpydoc
    - recommonmark
    - sphinx_rtd_theme
    - xarray
    - pip
    - pip:
        - spaceweather
