language: python
cache: pip
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - CFLAGS=-coverage
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U pytest pytest-cov codecov coveralls cpp-coveralls
  - pip install tox-travis
  - pip install scrutinizer-ocular
  - pip install -e '.[all]'
script:
  - py.test -v --doctest-glob='*.md' --cov src
  - coveralls --build-root=. --include=src --dump=cpp-coveralls.json
after_success:
  - coverage report
  - codecov
  - coveralls --merge=cpp-coveralls.json
  - ocular --data-file ".coverage"
before_deploy:
  # Builds wheels only with Python 3.7
  # cibuildwheel version and manylinux images to build Py34 wheels
  # alternative image sha256:
  # quay.io/pypa/manylinux1_i686@sha256:6616c1a4a93798214e86e964379cd2ee8163fe62af0751da2e8c682809d7c96c
  # quay.io/pypa/manylinux1_x86_64@sha256:e90db28d26e5558faa8d58ccd2e67d516ca83f793327df0ba48968a77485eb08
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      pip install cibuildwheel==0.12.0
      export CIBW_BUILD="cp34-*"
      export CIBW_MANYLINUX1_I686_IMAGE="quay.io/pypa/manylinux1_i686:2020-01-31-d8fa357"
      export CIBW_MANYLINUX1_X86_64_IMAGE="quay.io/pypa/manylinux1_x86_64:2020-01-31-d8fa357"
      cibuildwheel --output-dir dist
      unset CIBW_BUILD CIBW_MANYLINUX1_I686_IMAGE CIBW_MANYLINUX1_X86_64_IMAGE
      pip install -U cibuildwheel==1.1.0
      cibuildwheel --output-dir dist
      ls -alF dist/
    fi
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: Qn+CHsG2geZCeNCZKSrxd6+bENmQ0Tyc1oFMFP1UtRvjhnbzZRwXCgjsZoHHQwuy5yReN+z6PHJepl+TzgcoSQutBzE1NRSFLSW3TWNor3zevg5PS1JXIWat5fhoNc8s8OXVJKrha4wStN1B185z8+tXT5beyMYnnvacntTCU7Z0cwHd9PeEy2z0w5e9VPYu66AvCDioV0cflCvC6rh4WU83tFVRxuyz+9Mqk5ZgwA8/UyXFHj0MZilP8AdRHzVkZHHKtfc9Cd4UDjvdtJXsN+eVwDnVVf5/uyfNbkqcCFNhaLgDuTxyczN64GqRH3RailHy4Ec6cXIO40mFxzpR3duerSkb4oxbes0Eol9QcsJfVOIB0NbQDbIQdiAS2tWdFSID7Dy5P26m+WDp2yPr/YEePECcTEFOMVVlvd97OViULdVJ1pshOHSAh9Lmsvp9kRvPUiU9TjH7IPkGvEAwM1YzczbRuWRRm0l9MoWAeiSt7m2leG35AXQ14aVMwRQMxxDpCtd9ar/HbMHXhytbd9d8mwO5hxF5V/O8A19mYRRuel+haihj8xh3VEfeKlyV5YGaMFS8Eg4K+dLXBTIUtdHoIA6r1abiG7bVns3Vw5M5BmvR4WnKCz/EBLSRCGQixulgfbP2+svNQIg2h1vj4Dvq/+gFt9TjkHNXvsa5xBo=
    skip_existing: true
    skip_cleanup: true
    on:
      repo: st-bender/pynrlmsise00
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION == 3.7
  - provider: pypi
    user: __token__
    password:
      secure: m8BVzgg7zE1UKvSvjTRRKv2UfhEHt2tV6S6Ot3Oa9xVoJ+uk0EaIp1OfBunxT77fSvwcFnZR3i0VodPyE1zbzyffOagSPq/Z8MmjN9HnGMSIKrlhKuJ/K00xVRn1qAl1NKc6vg9WF+EW4rYxHPeFWEFcYZM8bnl6uoqgCNug9ML9QO0mX6BIWiFPhS+cXZC3HP3yD8RernWcl/6N8YXLgH9ShDkSCkXlcRKzfNyNRiPv17OdmAlf6SAzy6uEgfK/f63SSXkkMbH3WMcJjqSbMp1JD5q+rhd0ss9bpJCcrG3X5YyC3Q2KzJ3DBVhxYEd7/Ne2Qa+R96yqXYle7NBi09+EOd95a7RqsD3Uaj7yP96r51oIw13ZWAyifyjBDXJhvyFI0EVczfmXtSvuijOq+6oWIaeX3kXxSENspLF/YqcSHF5SqoyiRCx5D4e9/YYeibdT2wl1mMiu2K9Fy+VN+grZJAC1PQHE5w2iSAmXRRclVWkMVM7T8oXkBu1J6ZLFidns9jxvVqRQhAx6pgLWDFQ0zw0Wmai3wpZnmHlbGSAD9SXNjJy9XM2Px5ek2UPi72CnR7JtpHBE9TzHKnk4abRyYVbHEx29G+W1AlOYAezracjd7g/bQKt/BZblKgcSJVa0vvUJT8ZV/HR+QK/o8saR2yAImb3IwOUMyKf06QY=
    skip_existing: true
    skip_cleanup: true
    on:
      repo: st-bender/pynrlmsise00
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION == 3.7
